# Generated by Django 4.2.13 on 2024-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_author_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
