# Generated by Django 4.2.13 on 2024-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_content_post_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
