# Generated by Django 4.0.4 on 2024-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_types',
            field=models.CharField(blank=True, choices=[('M', 'Mpesa'), ('C', 'Credit Card')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Ok'), ('P', 'Pending'), ('C', 'Cancelled')], default='P', max_length=1, null=True),
        ),
    ]
