# Generated by Django 4.2.13 on 2024-09-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0003_alter_survey_interest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='survey',
            name='scheduled_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', null=True),
        ),
    ]
