# Generated by Django 4.2.13 on 2024-11-07 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0005_survey_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalmissionarydailyreport',
            old_name='content',
            new_name='challenges',
        ),
        migrations.RenameField(
            model_name='medicalmissionarydailyreport',
            old_name='date_posted',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='name',
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='appointment_day',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='appointments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='home_visited',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='homes_rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='homes_under_appointments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='homes_visited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='interest_phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='missionary_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='needs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='nurturing_rp_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='nurturing_rp_phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='people_attended',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='prayer_requests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='study',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='to_be_nurtured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
