# Generated by Django 4.2.13 on 2024-11-07 08:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0006_rename_content_medicalmissionarydailyreport_challenges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibleworkerdailyreport',
            old_name='content',
            new_name='challenges',
        ),
        migrations.RenameField(
            model_name='bibleworkerdailyreport',
            old_name='date_posted',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='medicalmissionarydailyreport',
            old_name='challenges',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='medicalmissionarydailyreport',
            old_name='timestamp',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='bibleworkerdailyreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bibleworkerdailyreport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bibleworkerdailyreport',
            name='studies_given',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='appointment_day',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='home_visited',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='homes_rejected',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='homes_under_appointments',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='interest_phone_number',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='missionary_name',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='nurturing_rp_name',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='nurturing_rp_phone_number',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='people_attended',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='prayer_requests',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='study',
        ),
        migrations.RemoveField(
            model_name='medicalmissionarydailyreport',
            name='to_be_nurtured',
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='appointment_day',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2024, 11, 7, 8, 11, 20, 255067, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='appointments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='home_visited',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='homes_rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='homes_under_appointments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='interest_phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='missionary_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='needs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='nurturing_rp_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='nurturing_rp_phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='people_attended',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='prayer_requests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='study',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleworkerdailyreport',
            name='to_be_nurtured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='medicalmissionarydailyreport',
            name='studies_given',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bibleworkerdailyreport',
            name='homes_visited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalmissionarydailyreport',
            name='homes_visited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
