# Generated by Django 4.2.13 on 2024-11-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0007_rename_content_bibleworkerdailyreport_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleworkerdailyreport',
            name='interest_phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bibleworkerdailyreport',
            name='nurturing_rp_phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
