# Generated by Django 4.0.4 on 2023-01-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
