# Generated by Django 4.0.4 on 2023-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_material_assignment_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
