# Generated by Django 4.0.4 on 2023-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_faculty_photo_remove_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default_faculty.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default_student.png', upload_to='profile_pics'),
        ),
    ]
