# Generated by Django 4.0.4 on 2023-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_assignment_datetime_alter_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='assignment',
        ),
        migrations.AddField(
            model_name='material',
            name='assignments',
            field=models.ManyToManyField(to='main.assignment'),
        ),
    ]
