# Generated by Django 4.0.4 on 2023-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_material_assignment_material_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
