# Generated by Django 4.0.4 on 2023-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_material_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
