# Generated by Django 4.0.4 on 2024-03-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['datetime'], 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-datetime'], 'verbose_name_plural': 'Submissions'},
        ),
    ]
