# Generated by Django 4.2.13 on 2024-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_course_membership_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='audio_links',
            field=models.ManyToManyField(to='main.audiolink'),
        ),
    ]
