# Generated by Django 4.2.13 on 2024-10-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_audiolink_assignment_audio_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='materialobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.material'),
        ),
    ]
