# Generated by Django 4.0.4 on 2024-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='budget_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='need',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
