# Generated by Django 4.0.4 on 2024-05-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('needs', '0002_rename_budget_price_need_price_need_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='received_payments',
            field=models.ManyToManyField(to='payment.payment'),
        ),
    ]
